### ISSUE TITLE
Night length (according to Umm AlQura)

### ISSUE THREAD

**Issue by foodornt** [alphahm/adhanpy#1]
Night length seems to be calculated as maghrib until sunrise
I believe the night ends when fajr begins (at least according to Umm AlQura, don't know about other methods), that's what I see in our masjid that got these calendar papers with prayer times
can we get that fixed?

**Comment by alphahm** [comment]
Hi, what is the issue exactly? do you get incorrect prayer times? Or do you just need the night length according to your parameters? If so, you can just obtain by just subtracting the two timestamps you would like to use.

**Comment by foodornt** [comment]
I apologize,
I did my research, apparently there is a khilaf about what is considered a night (ليل).
the method used in the library is considered to be one of the opinions,

You're right, subtracting fajr from isha gives the other opinion.

Thanks for the amazing library!
