### ISSUE TITLE
Support older Python versions

### ISSUE THREAD

**Issue by mmmoussa** [alphahm/adhanpy#7]
Al salam alaykum, thanks for porting adhan to Python! I had it on my todo list for a long time and unfortunately never got around to it.

I have a use case for this library in an environment where it is difficult to install Python versions above 3.9, and hence this library fails. From my quick testing so far it seems the main blocker to supporting older Python versions is the use of `match` statements. Would you be open to a PR that removes them and brings support for older Python versions?

**Comment by alphahm** [comment]
Waalikum salam, that's correct, match...case is only available from 3.10. I am not against supporting 3.9 as this still has security fixes support until somewhere in 2025. The more people this library helps, the better. Besides, as it stands, I am not entirely happy with the way the piece of code that uses the match...case looks at the moment...

We just need to find a nice and elegant way to refactor this, strategy pattern or factory perhaps withouth overengineering things... Also test everything. I need to have a think about this. In the meantime, let me know your thoughts, here or via a PR.

**Comment by alphahm** [comment]
Ok, released :). Thanks for your cooperation.
